namespace: famedly
name: dns
version: 0.1.0
readme: README.md
authors:
- Johanna Dorothea Reichmann <transcaffeine@finallycoffee.eu>
description: Roles for deploying and managing DNS infrastructure
license_file: 'LICENSE'
tags:
  - dns
dependencies:
  community.general: 3.8.0
  community.crypto: 1.9.5
  community.docker: 2.0.0
  community.postgres: 1.5.0
repository:    https://gitlab.com/famedly/infra/collections/dns
documentation: https://gitlab.com/famedly/infra/collections/dns
homepage:      https://gitlab.com/famedly/infra/collections/dns
issues:        https://gitlab.com/famedly/infra/collections/dns/-/issues
